kind: ConfigMap
apiVersion: v1
metadata:
  name: linkerd-grafana-config
data:
  grafana.ini: |-
    instance_name = linkerd-grafana

    [server]
    root_url = %(protocol)s://%(domain)s:/grafana/

    [analytics]
    check_for_updates = true