kind: ConfigMap
apiVersion: v1
metadata:
  name: linkerd-grafana-config
data:
  grafana.ini: |-
    [security]
    disable_gravatar = true

    [session]
    cookie_secure = true

    [panels]
    disable_sanitize_html = true