apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: grafana-ingress
  namespace: linkerd
  annotations:
    kubernetes.io/ingress.class: kong
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - grafana.jackhughes.dev
    secretName: grafana-tls
  rules:
  - host: grafana.jackhughes.dev
    http:
      paths:
      - backend:
          serviceName: linkerd-grafana
          servicePort: 3000
