apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: jack-hughes-dev-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: kong
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - jackhughes.dev
    secretName: jack-hughes-tls
  rules:
  - host: jackhughes.dev
    http:
      paths:
      - backend:
          serviceName: jh-front-end-svc
          servicePort: 80
